#!/bin/bash

#Check if all 3 arguments are given
if [ $# -ne 3 ]
then
        echo "Error: Missing arguments"
        echo "Usage: Dir-create.sh <directory_name> <start_number> <end_number>"
        exit 1
fi


# Get the arguments
directory_name=$1
start=$2
end=$3

# Create directories with dynamic name
for (( i=$start; i<=$end; i++ ))
do
        dir_name="$directory_name$i"
        mkdir $dir_name
        echo "Directory created: $dir_name"
done

echo "Done"
