pipeline {
    agent any
    
    environment {
        TF_VERSION = "1.0.0" // Replace with your desired Terraform version
        AWS_CREDENTIALS = credentials('AWS_Cred')
        AWS_REGION = "us-east-1" // Replace with your AWS region
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout your Terraform project from version control (e.g., Git)
                git 'https://github.com/PraveenKumar0796/First_project.git'
            }
        }
        
        stage('Terraform Init') {
            steps {
                // Install and configure Terraform
                script {
                    def tfHome = tool name: 'Terraform', type: 'org.jenkinsci.plugins.terraform.TerraformTool'
                    env.PATH = "${tfHome}:${env.PATH}"
                    
                    // Initialize Terraform
                    sh 'terraform init'
                }
            }
        }
        
        stage('Terraform Plan') {
            steps {
                // Generate and review Terraform plan
                script {
                    // Run terraform plan and save the output to a file
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        
        stage('Terraform Apply') {
            steps {
                // Apply Terraform changes
                script {
                    // Apply Terraform changes using the plan file generated earlier
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }
    
    post {
        always {
            // Clean up temporary files if needed
        }
    }
}
